services:
    platform:
        path:      /{page}
        defaults:  { _controller: OCUserBundle:User:index, page: 1 }
        requirements:
            page:  \d*
#    oc_user.example:
#        class: OC\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
