# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments: ['@request_stack', '@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }
    oc_platform.antispam:
        class:     OC\PlatformBundle\Antispam\OCAntispam
        arguments: ['@mailer', '50']
        calls:
            - [ setLocale, [ '%locale%' ] ]
        tags:
            -  { name: twig.extension }
    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: ['@mailer']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: ['@oc_platform.beta.html', '"2016-01-20"']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }
    oc_platform.censorship_processor:
        class:     OC\PlatformBundle\Bigbrother\CensorshipProcessor
        arguments: ['@mailer']
    oc_platform.bigbrother.censorship_listener:
        class:     OC\PlatformBundle\Bigbrother\CensorshipListener
        arguments: ['@oc_platform.censorship_processor', '[0, 1, 2]']
        tags:
            - { name: kernel.event_subscriber }
    oc_platform.json_paramconverter:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }